controller:
  ros__parameters:
    surge:
      Kp: 0.5 # 0.5 # 0.2 #5 # 0.5
      Ki: 0
      Kd: 0.7 # 0.002 # 0.02
      maxBack: -70
      maxFront: 70
    sway:
      Kp: 0.3 #0.5 # 0.04
      Ki: 0 # 0
      Kd: 0 #0.1 # 0.04
      maxBack: -70
      maxFront: 70
    heave:
      Kp: 0.6 #0.6 # 5
      Ki: 0.012 #0.012 #0.05 # 0
      Kd: 0.09 #0.09 # 2
      maxBack: -70
      maxFront: 70
    roll:
      Kp: 0.1 # 3
      Ki: 0
      Kd: 0.01
      maxBack: -20
      maxFront: 20
    pitch:
      Kp: 0.2 #0.08 # 0.1 # 3
      Ki: 0
      Kd: 0.02 #0.008
      maxBack: -40
      maxFront: 40
    yaw:
      Kp: 0.3
      Ki: 0
      Kd: 0.1
      maxBack: -40
      maxFront: 40
