controller:
  ros__parameters: 
    surge_CEM:
      surge_top:
        power_factor: 0.55
        backward_ratio: 1.100

      surge_left:
        power_factor: 1.25
        backward_ratio: 1.150
    
      surge_right:
        power_factor: 0.65
        backward_ratio: 0.950
    
      sway_back:
        power_factor: 0.440
        backward_ratio: 1.000
    
      sway_front:
        power_factor: 0.950
        backward_ratio: 1.000
    
      heave_left:
        power_factor: 0.950
        backward_ratio: 1.000
    
      heave_right:
        power_factor: 0.870
        backward_ratio: 1.000
    
      heave_back:
        power_factor: 0.984
        backward_ratio: 1.000
