---
vision:
  front_camera_config:
    img_height: 1100
    img_width: 2000
  bottom_camera_config:
    img_height: 404
    img_width: 644
  dvl_to_camera_vector:
    front:
      x: 55
      y: 7
      z: -7
    bottom:
      x: 13
      y: 9
      z: -3
  objects:
    - object_id: 0
      object_name: 'Bin'
      object_length: 80
      object_height: 60
      min_confidence: 0.5
    - object_id: 1
      object_name: 'Abydos_symbol_1'
      object_length: 50
      object_height: 50
      min_confidence: 0.2
    - object_id: 2
      object_name: 'Abydos_symbol_2'
      object_length: 50
      object_height: 50
      min_confidence: 0.2
    - object_id: 3
      object_name: 'Abydos_symbol_3'
      object_length: 10
      object_height: 10
      min_confidence: 0.5
    - object_id: 4
      object_name: 'Abydos_symbol_4'
      object_length: 0.6
      object_height: 1.3
      min_confidence: 0.5
    - object_id: 5
      object_name: 'Abydos_symbol_5'
      object_length: 10
      object_height: 10
      min_confidence: 0.5
    - object_id: 6
      object_name: 'Abydos_symbol_6'
      object_length: 10
      object_height: 10
      min_confidence: 0.5
    - object_id: 7
      object_name: 'Buoy'
      object_length: 122
      object_height: 122
      min_confidence: 0.2
    - object_id: 8
      object_name: 'Earth_symbol_1'
      object_length: 50
      object_height: 50
      min_confidence: 0.2
    - object_id: 9
      object_name: 'Earth_symbol_2'
      object_length: 50
      object_height: 50
      min_confidence: 0.2
    - object_id: 10
      object_name: 'Earth_symbol_3'
      object_length: 10
      object_height: 10
      min_confidence: 0.5
    - object_id: 11
      object_name: 'Earth_symbol_4'
      object_length: 10
      object_height: 10
      min_confidence: 0.5
    - object_id: 12
      object_name: 'Earth_symbol_5'
      object_length: 10
      object_height: 10
      min_confidence: 0.5
    - object_id: 13
      object_name: 'Earth_symbol_6'
      object_length: 10
      object_height: 10
      min_confidence: 0.5
    - object_id: 14
      object_name: 'Octagon'
      object_length: 10
      object_height: 10
      min_confidence: 0.5
    - object_id: 15
      object_name: 'Octagon_middle'
      object_length: 10
      object_height: 10
      min_confidence: 0.5
    - object_id: 16
      object_name: 'Sameer-s Foot'
      object_length: 10
      object_height: 10
      min_confidence: 1
    - object_id: 17
      object_name: 'Torpedo'
      object_length: 122
      object_height: 122
      min_confidence: 0.5
    - object_id: 18
      object_name: 'Torpedo_close'
      object_length: 30
      object_height: 30
      min_confidence: 0.5
    - object_id: 19
      object_name: 'Torpedo_closed'
      object_length: 10
      object_height: 10
      min_confidence: 0.5
    - object_id: 20
      object_name: 'Torpedo_open'
      object_length: 30
      object_height: 30
      min_confidence: 0.5
    - object_id: 21
      object_name: '5d'
      object_length: 35
      object_height: 20
      min_confidence: 0.5


    - object_id: 22
      object_name: 'Octagon_1'
      object_length: 50
      object_height: 50
      min_confidence: 0.5


    - object_id: 23
      object_name: 'Octagon_2'
      object_length: 50
      object_height: 50
      min_confidence: 0.5


    - object_id: 24
      object_name: 'Octagon_3'
      object_length: 50
      object_height: 50
      min_confidence: 0.5

    - object_id: 25
      object_name: 'Octagon_4'
      object_length: 50
      object_height: 50
      min_confidence: 0.5


    - object_id: 26
      object_name: 'Octagon_5'
      object_length: 50
      object_height: 50
      min_confidence: 0.5


    - object_id: 27
      object_name: 'Octagon_6'
      object_length: 50
      object_height: 50
      min_confidence: 0.5

    - object_id: 28
      object_name: 'Octagon_7'
      object_length: 50
      object_height: 50
      min_confidence: 0.5

    - object_id: 29
      object_name: 'Octagon_8'
      object_length: 50
      object_height: 50
      min_confidence: 0.5

    - object_id: 30
      object_name: 'Octagon'
      object_length: 270
      object_height: 270
      min_confidence: 0.5
  tasks:
  # Specify objects under each task in order of their training precision
  # and recall. Best trained objects first.
    - task_name: "Buoy"
      objects:
        - name: 'Abydos_symbol_1'
          rel_vector_from_task:
            x: -20
            y: 0
            z: 0
        - name: 'Abydos_symbol_2'
          rel_vector_from_task:
            x: -20
            y: 0
            z: 0
        - name: 'Earth_symbol_1'
          rel_vector_from_task:
            x: -20
            y: 0
            z: 30
        - name: 'Earth_symbol_2'
          rel_vector_from_task:
            x: -20
            y: 0
            z: 0
    - task_name: "Torpedo"
      objects:
        - name: 'Torpedo'
          rel_vector_from_task:
            x: 0
            y: 0
            z: 0
        - name: 'Torpedo_close'
          rel_vector_from_task:
            x: 0
            y: 0
            z: -30
        - name: 'Torpedo_open'
          rel_vector_from_task:
            x: 0
            y: 0
            z: 30
    - task_name: "Bin"
      objects:
        - name: "Bin"
          rel_vector_from_task:
            x: 27
            y: 13
            z: 0
    - task_name: "Octagon"
      objects:
        - name: "Octagon_1"
          rel_vector_from_task:
            x: 0
            y: 0
            z: 50
        - name: "Octagon_2"
          rel_vector_from_task:
            x: 0
            y: 0
            z: 50
        - name: "Octagon_3"
          rel_vector_from_task:
            x: 0
            y: 0
            z: 50
        - name: "Octagon_4"
          rel_vector_from_task:
            x: 0
            y: 0
            z: 50
        - name: "Octagon_5"
          rel_vector_from_task:
            x: 0
            y: 0
            z: 50
        - name: "Octagon_6"
          rel_vector_from_task:
            x: 0
            y: 0
            z: 50
        - name: "Octagon_7"
          rel_vector_from_task:
            x: 0
            y: 0
            z: 50
        - name: "Octagon_8"
          rel_vector_from_task:
            x: 0
            y: 0
            z: 50
        - name: "Octagon"
          rel_vector_from_task:
            x: 0
            y: 0
            z: 50

